/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export declare namespace IBundler {
  export type BundleStruct = {
    salt: PromiseOrValue<BytesLike>;
    bundle: PromiseOrValue<BytesLike>;
  };

  export type BundleStructOutput = [string, string] & {
    salt: string;
    bundle: string;
  };
}

export declare namespace ISBTHandler {
  export type DepositSBTParametersStruct = {
    token: PromiseOrValue<string>;
    tokenId: PromiseOrValue<BigNumberish>;
    bundle: IBundler.BundleStruct;
    network: PromiseOrValue<string>;
    receiver: PromiseOrValue<string>;
  };

  export type DepositSBTParametersStructOutput = [
    string,
    BigNumber,
    IBundler.BundleStructOutput,
    string,
    string
  ] & {
    token: string;
    tokenId: BigNumber;
    bundle: IBundler.BundleStructOutput;
    network: string;
    receiver: string;
  };

  export type WithdrawSBTParametersStruct = {
    token: PromiseOrValue<string>;
    tokenId: PromiseOrValue<BigNumberish>;
    tokenURI: PromiseOrValue<string>;
    bundle: IBundler.BundleStruct;
    originHash: PromiseOrValue<BytesLike>;
    receiver: PromiseOrValue<string>;
    proof: PromiseOrValue<BytesLike>;
  };

  export type WithdrawSBTParametersStructOutput = [
    string,
    BigNumber,
    string,
    IBundler.BundleStructOutput,
    string,
    string,
    string
  ] & {
    token: string;
    tokenId: BigNumber;
    tokenURI: string;
    bundle: IBundler.BundleStructOutput;
    originHash: string;
    receiver: string;
    proof: string;
  };
}

export interface SBTHandlerInterface extends utils.Interface {
  functions: {
    "__Bundler_init(address,address)": FunctionFragment;
    "bundleExecutorImplementation()": FunctionFragment;
    "depositSBT((address,uint256,(bytes32,bytes),string,string))": FunctionFragment;
    "determineProxyAddress(bytes32)": FunctionFragment;
    "facade()": FunctionFragment;
    "onERC721Received(address,address,uint256,bytes)": FunctionFragment;
    "withdrawSBT((address,uint256,string,(bytes32,bytes),bytes32,address,bytes))": FunctionFragment;
    "withdrawSBTBundle((address,uint256,string,(bytes32,bytes),bytes32,address,bytes))": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "__Bundler_init"
      | "__Bundler_init(address,address)"
      | "bundleExecutorImplementation"
      | "bundleExecutorImplementation()"
      | "depositSBT"
      | "depositSBT((address,uint256,(bytes32,bytes),string,string))"
      | "determineProxyAddress"
      | "determineProxyAddress(bytes32)"
      | "facade"
      | "facade()"
      | "onERC721Received"
      | "onERC721Received(address,address,uint256,bytes)"
      | "withdrawSBT"
      | "withdrawSBT((address,uint256,string,(bytes32,bytes),bytes32,address,bytes))"
      | "withdrawSBTBundle"
      | "withdrawSBTBundle((address,uint256,string,(bytes32,bytes),bytes32,address,bytes))"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "__Bundler_init",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "__Bundler_init(address,address)",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "bundleExecutorImplementation",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "bundleExecutorImplementation()",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "depositSBT",
    values: [ISBTHandler.DepositSBTParametersStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "depositSBT((address,uint256,(bytes32,bytes),string,string))",
    values: [ISBTHandler.DepositSBTParametersStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "determineProxyAddress",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "determineProxyAddress(bytes32)",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(functionFragment: "facade", values?: undefined): string;
  encodeFunctionData(functionFragment: "facade()", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "onERC721Received",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "onERC721Received(address,address,uint256,bytes)",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawSBT",
    values: [ISBTHandler.WithdrawSBTParametersStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawSBT((address,uint256,string,(bytes32,bytes),bytes32,address,bytes))",
    values: [ISBTHandler.WithdrawSBTParametersStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawSBTBundle",
    values: [ISBTHandler.WithdrawSBTParametersStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawSBTBundle((address,uint256,string,(bytes32,bytes),bytes32,address,bytes))",
    values: [ISBTHandler.WithdrawSBTParametersStruct]
  ): string;

  decodeFunctionResult(
    functionFragment: "__Bundler_init",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "__Bundler_init(address,address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bundleExecutorImplementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bundleExecutorImplementation()",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "depositSBT", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositSBT((address,uint256,(bytes32,bytes),string,string))",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "determineProxyAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "determineProxyAddress(bytes32)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "facade", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "facade()", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "onERC721Received",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onERC721Received(address,address,uint256,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawSBT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawSBT((address,uint256,string,(bytes32,bytes),bytes32,address,bytes))",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawSBTBundle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawSBTBundle((address,uint256,string,(bytes32,bytes),bytes32,address,bytes))",
    data: BytesLike
  ): Result;

  events: {
    "DepositedSBT(address,uint256,bytes32,bytes,string,string)": EventFragment;
    "Initialized(uint8)": EventFragment;
    "WithdrawnSBT(address,uint256,string,bytes32,bytes,bytes32,address,bytes)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "DepositedSBT"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "DepositedSBT(address,uint256,bytes32,bytes,string,string)"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Initialized(uint8)"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "WithdrawnSBT"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "WithdrawnSBT(address,uint256,string,bytes32,bytes,bytes32,address,bytes)"
  ): EventFragment;
}

export interface DepositedSBTEventObject {
  token: string;
  tokenId: BigNumber;
  salt: string;
  bundle: string;
  network: string;
  receiver: string;
}
export type DepositedSBTEvent = TypedEvent<
  [string, BigNumber, string, string, string, string],
  DepositedSBTEventObject
>;

export type DepositedSBTEventFilter = TypedEventFilter<DepositedSBTEvent>;

export interface InitializedEventObject {
  version: number;
}
export type InitializedEvent = TypedEvent<[number], InitializedEventObject>;

export type InitializedEventFilter = TypedEventFilter<InitializedEvent>;

export interface WithdrawnSBTEventObject {
  token: string;
  tokenId: BigNumber;
  tokenURI: string;
  salt: string;
  bundle: string;
  originHash: string;
  receiver: string;
  proof: string;
}
export type WithdrawnSBTEvent = TypedEvent<
  [string, BigNumber, string, string, string, string, string, string],
  WithdrawnSBTEventObject
>;

export type WithdrawnSBTEventFilter = TypedEventFilter<WithdrawnSBTEvent>;

export interface SBTHandler extends BaseContract {
  contractName: "SBTHandler";

  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: SBTHandlerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    __Bundler_init(
      bundleExecutorImplementation_: PromiseOrValue<string>,
      facade_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "__Bundler_init(address,address)"(
      bundleExecutorImplementation_: PromiseOrValue<string>,
      facade_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    bundleExecutorImplementation(overrides?: CallOverrides): Promise<[string]>;

    "bundleExecutorImplementation()"(
      overrides?: CallOverrides
    ): Promise<[string]>;

    depositSBT(
      params_: ISBTHandler.DepositSBTParametersStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "depositSBT((address,uint256,(bytes32,bytes),string,string))"(
      params_: ISBTHandler.DepositSBTParametersStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    determineProxyAddress(
      salt_: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    "determineProxyAddress(bytes32)"(
      salt_: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    facade(overrides?: CallOverrides): Promise<[string]>;

    "facade()"(overrides?: CallOverrides): Promise<[string]>;

    onERC721Received(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>,
      arg3: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "onERC721Received(address,address,uint256,bytes)"(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>,
      arg3: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    withdrawSBT(
      params_: ISBTHandler.WithdrawSBTParametersStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "withdrawSBT((address,uint256,string,(bytes32,bytes),bytes32,address,bytes))"(
      params_: ISBTHandler.WithdrawSBTParametersStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    withdrawSBTBundle(
      params_: ISBTHandler.WithdrawSBTParametersStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "withdrawSBTBundle((address,uint256,string,(bytes32,bytes),bytes32,address,bytes))"(
      params_: ISBTHandler.WithdrawSBTParametersStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  __Bundler_init(
    bundleExecutorImplementation_: PromiseOrValue<string>,
    facade_: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "__Bundler_init(address,address)"(
    bundleExecutorImplementation_: PromiseOrValue<string>,
    facade_: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  bundleExecutorImplementation(overrides?: CallOverrides): Promise<string>;

  "bundleExecutorImplementation()"(overrides?: CallOverrides): Promise<string>;

  depositSBT(
    params_: ISBTHandler.DepositSBTParametersStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "depositSBT((address,uint256,(bytes32,bytes),string,string))"(
    params_: ISBTHandler.DepositSBTParametersStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  determineProxyAddress(
    salt_: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<string>;

  "determineProxyAddress(bytes32)"(
    salt_: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<string>;

  facade(overrides?: CallOverrides): Promise<string>;

  "facade()"(overrides?: CallOverrides): Promise<string>;

  onERC721Received(
    arg0: PromiseOrValue<string>,
    arg1: PromiseOrValue<string>,
    arg2: PromiseOrValue<BigNumberish>,
    arg3: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "onERC721Received(address,address,uint256,bytes)"(
    arg0: PromiseOrValue<string>,
    arg1: PromiseOrValue<string>,
    arg2: PromiseOrValue<BigNumberish>,
    arg3: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  withdrawSBT(
    params_: ISBTHandler.WithdrawSBTParametersStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "withdrawSBT((address,uint256,string,(bytes32,bytes),bytes32,address,bytes))"(
    params_: ISBTHandler.WithdrawSBTParametersStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  withdrawSBTBundle(
    params_: ISBTHandler.WithdrawSBTParametersStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "withdrawSBTBundle((address,uint256,string,(bytes32,bytes),bytes32,address,bytes))"(
    params_: ISBTHandler.WithdrawSBTParametersStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    __Bundler_init(
      bundleExecutorImplementation_: PromiseOrValue<string>,
      facade_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    "__Bundler_init(address,address)"(
      bundleExecutorImplementation_: PromiseOrValue<string>,
      facade_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    bundleExecutorImplementation(overrides?: CallOverrides): Promise<string>;

    "bundleExecutorImplementation()"(
      overrides?: CallOverrides
    ): Promise<string>;

    depositSBT(
      params_: ISBTHandler.DepositSBTParametersStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    "depositSBT((address,uint256,(bytes32,bytes),string,string))"(
      params_: ISBTHandler.DepositSBTParametersStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    determineProxyAddress(
      salt_: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    "determineProxyAddress(bytes32)"(
      salt_: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    facade(overrides?: CallOverrides): Promise<string>;

    "facade()"(overrides?: CallOverrides): Promise<string>;

    onERC721Received(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>,
      arg3: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    "onERC721Received(address,address,uint256,bytes)"(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>,
      arg3: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    withdrawSBT(
      params_: ISBTHandler.WithdrawSBTParametersStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    "withdrawSBT((address,uint256,string,(bytes32,bytes),bytes32,address,bytes))"(
      params_: ISBTHandler.WithdrawSBTParametersStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    withdrawSBTBundle(
      params_: ISBTHandler.WithdrawSBTParametersStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    "withdrawSBTBundle((address,uint256,string,(bytes32,bytes),bytes32,address,bytes))"(
      params_: ISBTHandler.WithdrawSBTParametersStruct,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "DepositedSBT(address,uint256,bytes32,bytes,string,string)"(
      token?: null,
      tokenId?: null,
      salt?: null,
      bundle?: null,
      network?: null,
      receiver?: null
    ): DepositedSBTEventFilter;
    DepositedSBT(
      token?: null,
      tokenId?: null,
      salt?: null,
      bundle?: null,
      network?: null,
      receiver?: null
    ): DepositedSBTEventFilter;

    "Initialized(uint8)"(version?: null): InitializedEventFilter;
    Initialized(version?: null): InitializedEventFilter;

    "WithdrawnSBT(address,uint256,string,bytes32,bytes,bytes32,address,bytes)"(
      token?: null,
      tokenId?: null,
      tokenURI?: null,
      salt?: null,
      bundle?: null,
      originHash?: null,
      receiver?: null,
      proof?: null
    ): WithdrawnSBTEventFilter;
    WithdrawnSBT(
      token?: null,
      tokenId?: null,
      tokenURI?: null,
      salt?: null,
      bundle?: null,
      originHash?: null,
      receiver?: null,
      proof?: null
    ): WithdrawnSBTEventFilter;
  };

  estimateGas: {
    __Bundler_init(
      bundleExecutorImplementation_: PromiseOrValue<string>,
      facade_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "__Bundler_init(address,address)"(
      bundleExecutorImplementation_: PromiseOrValue<string>,
      facade_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    bundleExecutorImplementation(overrides?: CallOverrides): Promise<BigNumber>;

    "bundleExecutorImplementation()"(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    depositSBT(
      params_: ISBTHandler.DepositSBTParametersStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "depositSBT((address,uint256,(bytes32,bytes),string,string))"(
      params_: ISBTHandler.DepositSBTParametersStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    determineProxyAddress(
      salt_: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "determineProxyAddress(bytes32)"(
      salt_: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    facade(overrides?: CallOverrides): Promise<BigNumber>;

    "facade()"(overrides?: CallOverrides): Promise<BigNumber>;

    onERC721Received(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>,
      arg3: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "onERC721Received(address,address,uint256,bytes)"(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>,
      arg3: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    withdrawSBT(
      params_: ISBTHandler.WithdrawSBTParametersStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "withdrawSBT((address,uint256,string,(bytes32,bytes),bytes32,address,bytes))"(
      params_: ISBTHandler.WithdrawSBTParametersStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    withdrawSBTBundle(
      params_: ISBTHandler.WithdrawSBTParametersStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "withdrawSBTBundle((address,uint256,string,(bytes32,bytes),bytes32,address,bytes))"(
      params_: ISBTHandler.WithdrawSBTParametersStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    __Bundler_init(
      bundleExecutorImplementation_: PromiseOrValue<string>,
      facade_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "__Bundler_init(address,address)"(
      bundleExecutorImplementation_: PromiseOrValue<string>,
      facade_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    bundleExecutorImplementation(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "bundleExecutorImplementation()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    depositSBT(
      params_: ISBTHandler.DepositSBTParametersStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "depositSBT((address,uint256,(bytes32,bytes),string,string))"(
      params_: ISBTHandler.DepositSBTParametersStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    determineProxyAddress(
      salt_: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "determineProxyAddress(bytes32)"(
      salt_: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    facade(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "facade()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    onERC721Received(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>,
      arg3: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "onERC721Received(address,address,uint256,bytes)"(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      arg2: PromiseOrValue<BigNumberish>,
      arg3: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    withdrawSBT(
      params_: ISBTHandler.WithdrawSBTParametersStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "withdrawSBT((address,uint256,string,(bytes32,bytes),bytes32,address,bytes))"(
      params_: ISBTHandler.WithdrawSBTParametersStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    withdrawSBTBundle(
      params_: ISBTHandler.WithdrawSBTParametersStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "withdrawSBTBundle((address,uint256,string,(bytes32,bytes),bytes32,address,bytes))"(
      params_: ISBTHandler.WithdrawSBTParametersStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
