/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../common";

export declare namespace IBundler {
  export type BundleStruct = {
    salt: PromiseOrValue<BytesLike>;
    bundle: PromiseOrValue<BytesLike>;
  };

  export type BundleStructOutput = [string, string] & {
    salt: string;
    bundle: string;
  };
}

export declare namespace ISBTHandler {
  export type DepositSBTParametersStruct = {
    token: PromiseOrValue<string>;
    tokenId: PromiseOrValue<BigNumberish>;
    bundle: IBundler.BundleStruct;
    network: PromiseOrValue<string>;
    receiver: PromiseOrValue<string>;
  };

  export type DepositSBTParametersStructOutput = [
    string,
    BigNumber,
    IBundler.BundleStructOutput,
    string,
    string
  ] & {
    token: string;
    tokenId: BigNumber;
    bundle: IBundler.BundleStructOutput;
    network: string;
    receiver: string;
  };

  export type WithdrawSBTParametersStruct = {
    token: PromiseOrValue<string>;
    tokenId: PromiseOrValue<BigNumberish>;
    tokenURI: PromiseOrValue<string>;
    bundle: IBundler.BundleStruct;
    originHash: PromiseOrValue<BytesLike>;
    receiver: PromiseOrValue<string>;
    proof: PromiseOrValue<BytesLike>;
  };

  export type WithdrawSBTParametersStructOutput = [
    string,
    BigNumber,
    string,
    IBundler.BundleStructOutput,
    string,
    string,
    string
  ] & {
    token: string;
    tokenId: BigNumber;
    tokenURI: string;
    bundle: IBundler.BundleStructOutput;
    originHash: string;
    receiver: string;
    proof: string;
  };
}

export interface ISBTHandlerInterface extends utils.Interface {
  functions: {
    "depositSBT((address,uint256,(bytes32,bytes),string,string))": FunctionFragment;
    "withdrawSBT((address,uint256,string,(bytes32,bytes),bytes32,address,bytes))": FunctionFragment;
    "withdrawSBTBundle((address,uint256,string,(bytes32,bytes),bytes32,address,bytes))": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "depositSBT"
      | "depositSBT((address,uint256,(bytes32,bytes),string,string))"
      | "withdrawSBT"
      | "withdrawSBT((address,uint256,string,(bytes32,bytes),bytes32,address,bytes))"
      | "withdrawSBTBundle"
      | "withdrawSBTBundle((address,uint256,string,(bytes32,bytes),bytes32,address,bytes))"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "depositSBT",
    values: [ISBTHandler.DepositSBTParametersStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "depositSBT((address,uint256,(bytes32,bytes),string,string))",
    values: [ISBTHandler.DepositSBTParametersStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawSBT",
    values: [ISBTHandler.WithdrawSBTParametersStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawSBT((address,uint256,string,(bytes32,bytes),bytes32,address,bytes))",
    values: [ISBTHandler.WithdrawSBTParametersStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawSBTBundle",
    values: [ISBTHandler.WithdrawSBTParametersStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawSBTBundle((address,uint256,string,(bytes32,bytes),bytes32,address,bytes))",
    values: [ISBTHandler.WithdrawSBTParametersStruct]
  ): string;

  decodeFunctionResult(functionFragment: "depositSBT", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositSBT((address,uint256,(bytes32,bytes),string,string))",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawSBT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawSBT((address,uint256,string,(bytes32,bytes),bytes32,address,bytes))",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawSBTBundle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawSBTBundle((address,uint256,string,(bytes32,bytes),bytes32,address,bytes))",
    data: BytesLike
  ): Result;

  events: {
    "DepositedSBT(address,uint256,bytes32,bytes,string,string)": EventFragment;
    "WithdrawnSBT(address,uint256,string,bytes32,bytes,bytes32,address,bytes)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "DepositedSBT"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "DepositedSBT(address,uint256,bytes32,bytes,string,string)"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "WithdrawnSBT"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "WithdrawnSBT(address,uint256,string,bytes32,bytes,bytes32,address,bytes)"
  ): EventFragment;
}

export interface DepositedSBTEventObject {
  token: string;
  tokenId: BigNumber;
  salt: string;
  bundle: string;
  network: string;
  receiver: string;
}
export type DepositedSBTEvent = TypedEvent<
  [string, BigNumber, string, string, string, string],
  DepositedSBTEventObject
>;

export type DepositedSBTEventFilter = TypedEventFilter<DepositedSBTEvent>;

export interface WithdrawnSBTEventObject {
  token: string;
  tokenId: BigNumber;
  tokenURI: string;
  salt: string;
  bundle: string;
  originHash: string;
  receiver: string;
  proof: string;
}
export type WithdrawnSBTEvent = TypedEvent<
  [string, BigNumber, string, string, string, string, string, string],
  WithdrawnSBTEventObject
>;

export type WithdrawnSBTEventFilter = TypedEventFilter<WithdrawnSBTEvent>;

export interface ISBTHandler extends BaseContract {
  contractName: "ISBTHandler";

  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ISBTHandlerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    depositSBT(
      params_: ISBTHandler.DepositSBTParametersStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "depositSBT((address,uint256,(bytes32,bytes),string,string))"(
      params_: ISBTHandler.DepositSBTParametersStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    withdrawSBT(
      params_: ISBTHandler.WithdrawSBTParametersStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "withdrawSBT((address,uint256,string,(bytes32,bytes),bytes32,address,bytes))"(
      params_: ISBTHandler.WithdrawSBTParametersStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    withdrawSBTBundle(
      params_: ISBTHandler.WithdrawSBTParametersStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "withdrawSBTBundle((address,uint256,string,(bytes32,bytes),bytes32,address,bytes))"(
      params_: ISBTHandler.WithdrawSBTParametersStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  depositSBT(
    params_: ISBTHandler.DepositSBTParametersStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "depositSBT((address,uint256,(bytes32,bytes),string,string))"(
    params_: ISBTHandler.DepositSBTParametersStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  withdrawSBT(
    params_: ISBTHandler.WithdrawSBTParametersStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "withdrawSBT((address,uint256,string,(bytes32,bytes),bytes32,address,bytes))"(
    params_: ISBTHandler.WithdrawSBTParametersStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  withdrawSBTBundle(
    params_: ISBTHandler.WithdrawSBTParametersStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "withdrawSBTBundle((address,uint256,string,(bytes32,bytes),bytes32,address,bytes))"(
    params_: ISBTHandler.WithdrawSBTParametersStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    depositSBT(
      params_: ISBTHandler.DepositSBTParametersStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    "depositSBT((address,uint256,(bytes32,bytes),string,string))"(
      params_: ISBTHandler.DepositSBTParametersStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    withdrawSBT(
      params_: ISBTHandler.WithdrawSBTParametersStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    "withdrawSBT((address,uint256,string,(bytes32,bytes),bytes32,address,bytes))"(
      params_: ISBTHandler.WithdrawSBTParametersStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    withdrawSBTBundle(
      params_: ISBTHandler.WithdrawSBTParametersStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    "withdrawSBTBundle((address,uint256,string,(bytes32,bytes),bytes32,address,bytes))"(
      params_: ISBTHandler.WithdrawSBTParametersStruct,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "DepositedSBT(address,uint256,bytes32,bytes,string,string)"(
      token?: null,
      tokenId?: null,
      salt?: null,
      bundle?: null,
      network?: null,
      receiver?: null
    ): DepositedSBTEventFilter;
    DepositedSBT(
      token?: null,
      tokenId?: null,
      salt?: null,
      bundle?: null,
      network?: null,
      receiver?: null
    ): DepositedSBTEventFilter;

    "WithdrawnSBT(address,uint256,string,bytes32,bytes,bytes32,address,bytes)"(
      token?: null,
      tokenId?: null,
      tokenURI?: null,
      salt?: null,
      bundle?: null,
      originHash?: null,
      receiver?: null,
      proof?: null
    ): WithdrawnSBTEventFilter;
    WithdrawnSBT(
      token?: null,
      tokenId?: null,
      tokenURI?: null,
      salt?: null,
      bundle?: null,
      originHash?: null,
      receiver?: null,
      proof?: null
    ): WithdrawnSBTEventFilter;
  };

  estimateGas: {
    depositSBT(
      params_: ISBTHandler.DepositSBTParametersStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "depositSBT((address,uint256,(bytes32,bytes),string,string))"(
      params_: ISBTHandler.DepositSBTParametersStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    withdrawSBT(
      params_: ISBTHandler.WithdrawSBTParametersStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "withdrawSBT((address,uint256,string,(bytes32,bytes),bytes32,address,bytes))"(
      params_: ISBTHandler.WithdrawSBTParametersStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    withdrawSBTBundle(
      params_: ISBTHandler.WithdrawSBTParametersStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "withdrawSBTBundle((address,uint256,string,(bytes32,bytes),bytes32,address,bytes))"(
      params_: ISBTHandler.WithdrawSBTParametersStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    depositSBT(
      params_: ISBTHandler.DepositSBTParametersStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "depositSBT((address,uint256,(bytes32,bytes),string,string))"(
      params_: ISBTHandler.DepositSBTParametersStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    withdrawSBT(
      params_: ISBTHandler.WithdrawSBTParametersStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "withdrawSBT((address,uint256,string,(bytes32,bytes),bytes32,address,bytes))"(
      params_: ISBTHandler.WithdrawSBTParametersStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    withdrawSBTBundle(
      params_: ISBTHandler.WithdrawSBTParametersStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "withdrawSBTBundle((address,uint256,string,(bytes32,bytes),bytes32,address,bytes))"(
      params_: ISBTHandler.WithdrawSBTParametersStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
