/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { Hashes, HashesInterface } from "../../../contracts/utils/Hashes";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    name: "usedHashes",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class Hashes__factory {
  static readonly abi = _abi;
  static createInterface(): HashesInterface {
    return new utils.Interface(_abi) as HashesInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): Hashes {
    return new Contract(address, _abi, signerOrProvider) as Hashes;
  }
}
